server:
  port: 8000
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mariadb://localhost:3308/bank
    username: root
    password: devpassword
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    platform: mariadb
    database-platform: org.hibernate.dialect.MariaDBDialect
